/*
 * Copyright 2020 Deephaven Data Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.deephaven.plugins.email;

import java.util.Optional;
import org.immutables.value.Value.Check;
import org.immutables.value.Value.Immutable;
import org.immutables.value.Value.Parameter;

/** The trailer is the final HTML element in the {@code <body>} tag. */
@Immutable
public abstract class Trailer {

  /**
   * The empty trailer.
   *
   * @return the trailer
   */
  public static Trailer none() {
    return ImmutableTrailer.builder().build();
  }

  /**
   * The Deephaven trailer.
   *
   * @return the trailer
   */
  public static Trailer deephaven() {
    return ImmutableTrailer.builder()
        .html(
            "<p style=\"color: #929192;\"><em>This message was generated by the <a href=\"https://deephaven.io\" style=\"color: #3a658a;\">Deephaven</a> Report Plugin.</em></p>")
        .build();
  }

  /**
   * Constructs a new trailer.
   *
   * @param html the html
   * @return the trailer
   */
  public static Trailer of(String html) {
    return ImmutableTrailer.builder().html(html).build();
  }

  /**
   * The optional trailer HTML.
   *
   * @return the html
   */
  @Parameter
  public abstract Optional<String> html();

  @Check
  final void check() {
    if (html().isPresent() && html().get().isEmpty()) {
      throw new IllegalArgumentException("html, if present, must be non-empty");
    }
  }
}
