/*
 * Copyright 2022 Deephaven Data Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.deephaven.plugins.html

import org.junit.jupiter.api.Test

import java.nio.file.Files
import java.nio.file.Path
import java.nio.charset.StandardCharsets
import java.time.Instant

import static io.deephaven.plugins.report.Functions.item
import static io.deephaven.plugins.report.Functions.report
import static org.assertj.core.api.Assertions.assertThat

class HTMLTest {

	@Test
	void saveTest1() {
		Path tmpDir = Files.createTempDirectory("saveTest1")
		Path tmpFile = Files.createTempFile(tmpDir, "saveTest1", ".html")

		def test_report = report("The report", item("Simple text"), Instant.EPOCH)
		HTMLFile.builder().lockType(HTMLFile.LockType.NONE).addReports(test_report).build().save(tmpFile.toString())
		def lines = Files.readAllLines(tmpFile, StandardCharsets.UTF_8)
		final String html = String.join("\n", lines)
		assertThat(html).isEqualTo("<html>\n" +
				" <head>\n" +
				"  <style>\n" +
				"   table {\n" +
				"     border-collapse: collapse;\n" +
				"     font-variant-numeric: tabular-nums;\n" +
				"     border-color: #c0bfbf;\n" +
				"     margin: 5px 0;\n" +
				"   }\n" +
				"   \n" +
				"   table tbody td,\n" +
				"   table thead th {\n" +
				"     padding: 2px;\n" +
				"   }\n" +
				"   \n" +
				"   table thead th {\n" +
				"     background-color: #3a658a;\n" +
				"     color: #fcfcfa;\n" +
				"   }\n" +
				"   \n" +
				"   table tbody tr:nth-child(even) {\n" +
				"     background-color: #f0f0ee;\n" +
				"   }\n" +
				"   \n" +
				"   h1,\n" +
				"   h2,\n" +
				"   h3,\n" +
				"   h4,\n" +
				"   h5,\n" +
				"   h6 {\n" +
				"     color: #3a658a;\n" +
				"     margin-top: 5px;\n" +
				"     margin-bottom: 0;\n" +
				"   }\n" +
				"   \n" +
				"   ul {\n" +
				"     padding-top: 5px;\n" +
				"     padding-bottom: 10px;\n" +
				"   }\n" +
				"  </style>\n" +
				" </head>\n" +
				" <body>\n" +
				"  <div data-deephaven-type=\"report\">\n" +
				"   <!-- generated at 1970-01-01T00:00:00Z -->\n" +
				"   <!-- Report{title=The report, item=Text{attributes={}, value=Simple text}, timestamp=1970-01-01T00:00:00Z} -->\n" +
				"   <!-- report(&quot;The report&quot;, &quot;Simple text&quot;) -->\n" +
				"   <h1>The report</h1>\n" +
				"   <div data-deephaven-type=\"text\">Simple text</div></div>\n" +
				"  <div data-deephaven-type=\"trailer\"><p style=\"color: #929192;\"><em>This message was generated by the <a href=\"https://deephaven.io\" style=\"color: #3a658a;\">Deephaven</a> Report Plugin.</em></p></div>\n" +
				" </body>\n" +
				"</html>")
	}
}
